### ISSUE TITLE
Crash when taking picture or selecting from Library

### ISSUE THREAD

**Issue by dmoczulski** [AlexLittlejohn/ALCameraViewController#11]
iOS 9.1, imported using CocoaPods, doesn't matter what I set target OS to.  Every time I take a picture or select from library, it crashes with:

'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </var/mobile/Containers/Bundle/Application/[MY_APP_INFO_HERE].app/Frameworks/ALCameraViewController.framework> (loaded)' with name 'ALConfirmViewController''

It doesn't look like the XIB file makes it over when importing from CocoaPods?

**Comment by fatihyildizhan** [comment]
It can be related to selected module?
![module](https://cloud.githubusercontent.com/assets/602600/11320444/ab3b4e26-90a0-11e5-9356-f84bf8772f39.png)

**Comment by dmoczulski** [comment]
I was just following the usage instructions.  I'm calling it from a button in a view, should that matter?

**Comment by phalladar** [comment]
I'm having the same problem. Not sure what happened as it seems to have started happening after the most recent commit.

**Comment by noctivityinc** [comment]
Same here.  Followed the instructions in the readme 100%.  I dont see anything related to selecting a module.  Also, the readme said nothing about having to import ALCameraViewController to get the code to work.  Maybe some other imports are required?

**Comment by phalladar** [comment]
There aren't any other required imports. It just looks like the xib was left out of the pod this update. Download the repo and add the xib into the Pod manually for now and it'll work.

**Comment by AlexLittlejohn** [comment]
Apologies, i have issued a hotfix v 1.0.11 to rectify this issue. If you run pod update on your project again it should be fixed

**Comment by noctivityinc** [comment]
Thanks but now when we try to use the load picture library button from the screen nothing happens and we get this every few seconds in the output log:

2015-11-22 13:16:21.372 Wecora[2633:1183360] Received memory warning.
2015-11-22 13:16:37.488 Wecora[2633:1183360] Received memory warning.



On November 22, 2015 at 12:09:05 PM, Alex Littlejohn (notifications@github.com) wrote:

Apologies, i have issued a hotfix v 1.0.11 to rectify this issue. If you run pod update on your project again it should be fixed

**Comment by phalladar** [comment]
You probably have a lot of photos on your device @noctivityinc. @AlexLittlejohn [just merged into the `develop` branch](https://github.com/AlexLittlejohn/ALCameraViewController/pull/13) a PR I made to make photo library loading asynchronous — seems to have fixed the memory warning problem for me.

**Comment by noctivityinc** [comment]
Looks like he merged it into the master branch.  Just pod update and tried it - no dice.  Images never load from image gallery.  I have tens of thousands and they are pulled from iCloud, so not sure if that’s a factor.




Joshua Lippiner 
.:t 704.323.5661
.:e jlippiner@noctivity.com



On November 22, 2015 at 1:49:52 PM, Joshua Auriemma (notifications@github.com) wrote:

You probably have a lot of photos on your device @noctivityinc. @AlexLittlejohn just merged into the develop branch a PR I made to make photo library loading asynchronous — seems to have fixed the memory warning problem for me.

**Comment by ijemmao** [comment]
Unless I'm doing something wrong in 2016, my program is still crashing when I try to select an image on the simulator. If there's an update I can use, any info would be very helpful.
